### ISSUE TITLE
memory allocation failed

### ISSUE THREAD

**Issue by Ladbaby** [spieglt/FlyingCarpet#54] opened 2023-10-24 13:11 UTC
First of all, Thanks for making this amazing app, I absolutely love it!

The problem occurred when I try to transfer from Android 13 to Ubuntu 22.04 LTS, a 818 MB .mp4 video file, the Linux app crashed after the Android had connected to the hotspot:

```
$ flying-carpet                                 
memory allocation of 3511553999805349888 bytes failed
[1]    30333 IOT instruction  flying-carpet
```

Version information:

- Android: v7.1 from Google Play
- Linux: v7.1 AppImage version

In fact, the .deb version of Linux client also suffered from the same issue.

Also, I tried a 9.8MB .jpg file, which is smaller, and it succeeded.

PS: I also met the same problem as in #51. Although I'm a Windows user most of the time, it would be great if FlyingCarpet can also work flawlessly under Linux (like it does under Windows)

**Comment by spieglt** [comment] 2023-10-24 22:57
Thanks for the kind words! Very unfortunate to see an allocation error like that though.... Can you possibly send me the exact size in bytes of the .mp4 so I can reproduce? This and #51 are next on my list.

**Comment by Ladbaby** [comment] 2023-10-25 03:25
It's 817597378 bytes in size (info from `wc -c`). Glad to hear the progress on fixing them :)

**Comment by spieglt** [comment] 2023-10-25 04:14
I'm not able to replicate so far. Can you send the output of the Android side when it crashes? Does changing the filename to `file.mp4` change the behavior? And none of the transfer happens, it crashes immediately?

**Comment by Ladbaby** [comment] 2023-10-26 00:57
Oh it's the file name that caused the error! Sorry for my misleading

I tried several file names, maybe it's caused by non-ASCII characters:

- `文字 2023.mp4`: original file name, failed
- `文字.mp4`: only the non-ASCII characters, failed with the same error above
- `2023.mp4`: succeeded
- `2023 12.mp4`: a name contains a space, succeeded
- `file.mp4`: succeeded

As for the output, the Linux client crashed and leave the above memory allocation failed error in the terminal, and the Android client's last output is `Transfer error: Connection reset`

There's one more special case when the file name is only 1 non-ASCII character `我.mp4` (the original file name contains 2), the Linux client's GUI didn't crash, and the output is:

```
Starting hotspot flyingCarpet_458d
Waiting for connection...
Connection accepted
=========================
Receiving file 1 of 1.
Filename: 我.m
File size: 8085087231.04GB
```

the file size is wrong, also the filename is missing the `p4` at the tail. The output from the terminal is also different:

```
thread 'tokio-runtime-worker' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:524:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The Android client output the same `Transfer error: Connection reset` error in this case

**Comment by spieglt** [comment] 2023-10-26 03:28
Not misleading at all, very grateful for you uncovering the bug. I found the problem, I wasn't handling the size of non-ASCII strings properly on Android. I'll fix it and get an updated Android version out soon. I should probably also move to a more mature transfer protocol at some point. Thanks again!

**Comment by Ladbaby** [comment] 2023-10-26 03:46
My pleasure, looking forward to the update!

**Comment by spieglt** [comment] 2023-10-27 01:09
[Version 7.2](https://github.com/spieglt/FlyingCarpet/releases/download/v7.1/android_FlyingCarpet_7.2.0.apk) is available on the [releases](https://github.com/spieglt/FlyingCarpet/releases) page and should be on the Play Store soon. Please let me know if this fixes the filename issue, thanks!

**Comment by Ladbaby** [comment] 2023-10-27 02:33
Have tried the Version 7.2 of Android client, and I'm pretty sure it fixes the filename issue (even tried filename with emoji `文字🌍.mp4`). Thanks for your active maintenance👍

**Comment by spieglt** [comment] 2023-10-27 14:09
Closing this since the other issue is being tracked in #51.

**Closed by spieglt** 2023-10-27 14:09 UTC
